FROM node:22-alpine

WORKDIR /app

COPY . .

RUN npm install -g pnpm
RUN pnpm install
RUN pnpm --filter http-layer build

ENV DATABASE_URL="postgresql://postgres:shine@postgres_db:5432/week27.2"

EXPOSE 5000
CMD [ "sh" , "-c" , "pnpm run db:generate && pnpm --filter http-layer start" ]
